////////////////////////////////////////////////////////////////////////
// Class:       TrackAnalyzer
// Module Type: analyzer
// File:        TrackAnalyzer_module.cc
//
// Generated at Tue Nov 10 13:06:09 2015 by Wesley Ketchum using artmod
// from cetpkgsupport v1_08_07.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "art/Framework/Services/Optional/TFileService.h"

#include "TTree.h"

#include "TrackAnalysis/TrackAnalysis.hh"

namespace trk {
  class TrackAnalyzer;
}

class trk::TrackAnalyzer : public art::EDAnalyzer {
public:
  explicit TrackAnalyzer(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  TrackAnalyzer(TrackAnalyzer const &) = delete;
  TrackAnalyzer(TrackAnalyzer &&) = delete;
  TrackAnalyzer & operator = (TrackAnalyzer const &) = delete;
  TrackAnalyzer & operator = (TrackAnalyzer &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void reconfigure(fhicl::ParameterSet const & p) override;

private:

  // Declare member data here.
  trk::TrackAnalysis fMyAnalysisObj;
  
};


trk::TrackAnalyzer::TrackAnalyzer(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{
  art::ServiceHandle<art::TFileService> tfs;
  fMyAnalysisObj.SetupOutputTree(tfs->make<TTree>("myanatree","MyAnalysis Tree"));
}

void trk::TrackAnalyzer::analyze(art::Event const & e)
{
  fMyAnalysisObj.RunAnalysis();
}

void trk::TrackAnalyzer::reconfigure(fhicl::ParameterSet const & p)
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(trk::TrackAnalyzer)
