////////////////////////////////////////////////////////////////////////
// Class:       TrackAnalyzer
// Module Type: analyzer
// File:        TrackAnalyzer_module.cc
//
// Generated at Tue Nov 10 13:06:09 2015 by Wesley Ketchum using artmod
// from cetpkgsupport v1_08_07.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "art/Framework/Services/Optional/TFileService.h"

#include "TTree.h"

#include "TrackAnalysis/TrackAnalysis.hh"
#include "Geometry/Geometry.h"

namespace trk {
  class TrackAnalyzer;
}

class trk::TrackAnalyzer : public art::EDAnalyzer {
public:
  explicit TrackAnalyzer(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  TrackAnalyzer(TrackAnalyzer const &) = delete;
  TrackAnalyzer(TrackAnalyzer &&) = delete;
  TrackAnalyzer & operator = (TrackAnalyzer const &) = delete;
  TrackAnalyzer & operator = (TrackAnalyzer &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void reconfigure(fhicl::ParameterSet const & p) override;

private:

  // Declare member data here.
  trk::TrackAnalysis fAlg;

  std::vector<std::string> fTrackModuleLabels;
  
};


trk::TrackAnalyzer::TrackAnalyzer(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{
  art::ServiceHandle<art::TFileService> tfs;
  fAlg.SetupOutputTree(tfs->make<TTree>("myanatree","MyAnalysis Tree"));
  this->reconfigure(p);
}

void trk::TrackAnalyzer::analyze(art::Event const & e)
{

  fAlg.SetRunEvent(e.run(),e.event());
  
  std::vector< std::vector<recob::Track> > trackVectors;
  for(size_t i_l=0; i_l<fTrackModuleLabels.size(); ++i_l){
    art::Handle< std::vector<recob::Track> > trackHandle;
    e.getByLabel(fTrackModuleLabels[i_l],trackHandle);
    trackVectors.push_back(*trackHandle);
  }
  
  art::ServiceHandle<geo::Geometry> geoHandle;

  fAlg.ProcessTracks(trackVectors,*geoHandle);

}

void trk::TrackAnalyzer::reconfigure(fhicl::ParameterSet const & p)
{
  fAlg.Configure(p.get<fhicl::ParameterSet>("TrackAnalysisAlg"));
  fTrackModuleLabels = p.get< std::vector<std::string> >("TrackModuleLabels");
}

DEFINE_ART_MODULE(trk::TrackAnalyzer)
